export const productsItem = [
  {
    id: 1,
    title: "I'm product 1",
    price: 19.99,
    fullprice: 19.99,
    color: "blue",
    size: "0-3m",
    description: "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
    category: "Tshirts",
    image: "https://skillkamp-api.com/static/45d10e_11ee24bab35748af871e855fa259b6ab_mv2.jpg",
    rating: {
      rate: 3.9,
      count: 120,
    },
  },
  {
    id: 2,
    title: "I'm product 2",
    price: 19.99,
    fullprice: 19.99,
    color: "blue",
    size: "0-3m",
    description:
      "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
    category: "Tshirts",
    image: "https://skillkamp-api.com/static/45d10e_c59544c57e0943fdab8d109f81174032_mv2.jpg",
    rating: {
      rate: 4.1,
      count: 259,
    },
  },
  {
    id: 3,
    title: "I'm product 3",
    price: 19.99,
    fullprice: 19.99,
    size: "3-6m",
    color: "blue",
    description:
      "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
    category: "Tshirts",
    image: "https://skillkamp-api.com/static/45d10e_3db73503839540b29a3479fcdf8be0ed_mv2.jpg",
    rating: {
      rate: 4.7,
      count: 500,
    },
  },
  {
    id: 4,
    title: "I'm product 4",
    price: 19.99,
    fullprice: 19.99,
    color: "blue",
    size: "3-6m",
    description:
      "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
    category: "Tshirts",
    image: "https://skillkamp-api.com/static/45d10e_d1b99b25e1d64f8e9944be79633a0f0a_mv2.jpg",
    rating: {
      rate: 2.1,
      count: 430,
    },
  },
  {
    id: 5,
    title: "I'm product 5",
    price: 19.99,
    fullprice: 19.99,
    size: "6-12m",
    color: "cream",
    description:
      "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
    category: "Tshirts",
    image: "https://skillkamp-api.com/static/45d10e_65b8703bd96b4553940f9304982283e5_mv2.jpg",
    rating: {
      rate: 4.6,
      count: 400,
    },
  },
  {
    id: 6,
    title: "I'm product 6",
    price: 19.99,
    fullprice: 19.99,
    color: "cream",
    size: "6-12m",
    description:
      "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
    category: "Tshirts",
    image: "https://skillkamp-api.com/static/45d10e_0d415a0c8f114c4592cab54a73662f7b_mv2.jpg",
    rating: {
      rate: 3.9,
      count: 70,
    },
  },
  {
    id: 7,
    title: "I'm product 7",
    price: 17.99,
    fullprice: 19.99,
    color: "cream",
    size: "6-12m",
    description:
      "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
    category: "Bodysuits",
    image: "https://skillkamp-api.com/static/45d10e_821d610d39ab4c78b5900735ffe1d7c3_mv2.jpg",
    rating: {
      rate: 3,
      count: 400,
    },
  },
  {
    id: 8,
    title: "I'm product 8",
    price: 19.99,
    fullprice: 19.99,
    size: "12-18m",
    color: "cream",
    description: "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
    category: "Bodysuits",
    image: "https://skillkamp-api.com/static/45d10e_df80e10017c641deaeedd262f1dd8484_mv2.jpg",
    rating: {
      rate: 1.9,
      count: 100,
    },
  },
  {
    id: 9,
    title: "I'm product 9",
    price: 19.99,
    fullprice: 19.99,
    size: "18-24m",
    color: "cream",
    description:
      "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
    category: "Bodysuits",
    image: "https://skillkamp-api.com/static/45d10e_fcd30400f4324f10a7918afec81eb2d0_mv2.jpg",
    rating: {
      rate: 3.3,
      count: 203,
    },
  },
  {
    id: 10,
    title: "I'm product 10",
    price: 19.99,
    fullprice: 19.99,
    color: "cream",
    size: "2y",
    description:
      "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
    category: "Bodysuits",
    image: "https://skillkamp-api.com/static/45d10e_5acc5d5c05d44e3792fd312042c4422c_mv2.jpg",
    rating: {
      rate: 2.9,
      count: 470,
    },
  },
  {
    id: 11,
    title: "I'm product 11",
    price: 17.99,
    fullprice: 19.99,
    color: "cream",
    size: "2y",
    description:
      "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
    category: "Bodysuits",
    image: "https://skillkamp-api.com/static/45d10e_69e4887cfeec4dcab8a7b1dad2fea9ab_mv2.jpg",
    rating: {
      rate: 4.8,
      count: 319,
    },
  },
  {
    id: 12,
    title: "I'm product 12",
    price: 19.99,
    fullprice: 19.99,
    color: "cream",
    size: "3y",
    description: "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    category: "Bodysuits",
    image: "https://skillkamp-api.com/static/45d10e_be60de18a2d84d52b23849a980828b54_mv2.jpg",
    rating: {
      rate: 4.8,
      count: 400,
    },
  },
];
